name: Unzip File

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Extract ZIP
        run: unzip file.zip -d extracted

      - name: Commit extracted files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add extracted
          git commit -m "Unzip file.zip into extracted folder" || echo "No changes to commit"
          git push
